package cli

// CommandInfo describes one hawp command for both the human --help text
// and the machine-readable `hawp commands --json` output — a single
// source of truth so the two can never drift apart.
type CommandInfo struct {
	Name        string   `json:"name"`
	Usage       string   `json:"usage"`
	Description string   `json:"description"`
	Flags       []string `json:"flags,omitempty"`
	ExitCodes   string   `json:"exitCodes"`
	Available   bool     `json:"available"`
}

// ExitCodeConvention documents the exit-code meaning shared by every
// validating/mutating command, for agents that branch on exit status
// rather than parsing text output.
const ExitCodeConvention = "0 = success/no issues; 1 = issues found or command-specific failure; 2 = usage error or guarded refusal (e.g. dirty worktree)"

// Registry is every command hawp currently supports, available or planned.
// Keep this in sync with helpText() — commands_test.go checks the two
// against each other.
var Registry = []CommandInfo{
	{Name: "uuid", Usage: "hawp uuid [--short]", Description: "Generate a work item UUID.", Flags: []string{"--short: print the 8-char display form"}, ExitCodes: "0 always", Available: true},
	{Name: "links check", Usage: "hawp links check", Description: "Validate local markdown links under .hawp/, docs/, and README.md.", ExitCodes: "0 = no broken links; 1 = broken links found", Available: true},
	{Name: "links clean", Usage: "hawp links clean [--apply]", Description: "Repairs broken local markdown links found by links check: relinks to the file if exactly one match exists elsewhere in the repo by base name, otherwise neutralizes it (drops the link syntax, keeps the visible text — \"[guide](gone.md)\" -> \"guide\"). Dry-run by default; --apply writes the changes. Never touches archival dirs (.hawp/work/closed, evidence, notes, status) — frozen history may reference removed paths by design.", Flags: []string{"--apply: write the changes (default is dry-run, report only)"}, ExitCodes: "0 = nothing to clean, or changes applied; 1 = dry-run found pending changes", Available: true},
	{Name: "kit validate", Usage: "hawp kit validate [--kit-path <path>]", Description: "Validate .hawp/kit/ structure: file naming, required files, internal links.", Flags: []string{"--kit-path <path>: override the default .hawp/kit location"}, ExitCodes: "0 = no issues; 1 = issues found", Available: true},
	{Name: "kit normalize", Usage: "hawp kit normalize [--apply|--dry-run] [--kit-path <path>]", Description: "Normalize .hawp/kit/ file names and internal links. Dry-run by default.", Flags: []string{"--apply: perform renames/link rewrites (requires a clean git worktree)", "--dry-run: report planned changes only (default)", "--kit-path <path>: override the default .hawp/kit location"}, ExitCodes: "0 = success; 1 = error (e.g. dirty worktree, rename conflict)", Available: true},
	{Name: "work validate", Usage: "hawp work validate [--work-root <path>] [--hawp-root <path>]", Description: "Backlog/plan/evidence integrity: backlog consistency, closed-task completeness, evidence links, verification clarity, dead links.", Flags: []string{"--work-root <path>: path to a .hawp/work directory", "--hawp-root <path>: path to a .hawp directory (validates <path>/work)"}, ExitCodes: "0 = PASS or WARN; 1 = FAIL", Available: true},
	{Name: "work new", Usage: `hawp work new "<title>" [--type task|bug|improvement|feature|fix|test|infrastructure|release|decision] [--input "<verbatim request>"] [--hawp-root <path>]`, Description: "Scaffold the intake step: generates a UUID, writes an investigation plan file from the intake template, and adds a status=inbox row to BACKLOG.md's Active Work table. Does not investigate or plan for you — see .hawp/kit/usage/intake-workflow.md for the next steps.", Flags: []string{`title (positional, required): the work item's title`, "--type <type>: BACKLOG.md Type column value (default: task)", "--input <text>: the original request, verbatim, recorded in the plan file's Input section (default: title)", "--hawp-root <path>: path to a .hawp directory (writes to <path>/work)"}, ExitCodes: "0 = success; 1 = error (e.g. missing title, slug collision)", Available: true},
	{Name: "work normalize", Usage: "hawp work normalize [--dry-run|--apply] [--validate] [--format text|json] [options]", Description: "Detect and (with --apply) fix work-record drift: missing fields, malformed IDs, missing closed-plan sections, stale references.", Flags: []string{"--dry-run: detection only (default)", "--apply: normalize closed records (requires a clean git worktree unless --force-dirty)", "--validate: run a work:validate summary afterwards", "--format text|json: dry-run report format", "--output <path>: write the report to a file", "--export-plan <path>: write the detected fix plan as JSON", "--export-research-queue <path>: write ambiguous verification claims as JSON", "--force-dirty: skip the apply-mode clean-worktree guard"}, ExitCodes: "0 = success; 1 = error; 2 = apply refused on a dirty worktree", Available: true},
	{Name: "check", Usage: "hawp check", Description: "Composite validation: kit validate + work validate + links check in one pass.", ExitCodes: "0 = all three passed; 1 = at least one failed", Available: true},
	{Name: "init", Usage: "hawp init [--provider <name>|all]", Description: "Provision ~/.hawp/ (ONNX Runtime + embedding model), sync .hawp/kit/ from the latest release, and optionally write MCP server configs for AI providers. File-writing providers: claude (.mcp.json), cursor (.cursor/mcp.json), codex (codex.toml); continue prints manual instructions. 'all' covers claude + cursor + codex + continue. Idempotent — re-running skips assets already installed.", Flags: []string{"--provider <name>: write MCP config for this provider (repeatable); 'all' expands to claude + cursor + codex + continue"}, ExitCodes: "0 = all assets ready; 1 = one or more assets failed", Available: true},
	{Name: "mcp", Usage: "hawp mcp", Description: "Start a stdio MCP server (JSON-RPC 2.0) for use with AI agents (Claude Code, Cursor, Continue, etc.). Exposes three tools: hawp_search, hawp_work_new, hawp_work_validate. Wire up via `hawp init --provider <name>` or manually add the server entry to your provider's MCP config.", ExitCodes: "0 = clean shutdown (stdin closed); 1 = fatal error", Available: true},
	{Name: "version", Usage: "hawp version", Description: "Print the running binary's version (\"dev\" for local, non-release builds).", ExitCodes: "0 always", Available: true},
	{Name: "update", Usage: "hawp update [--check] [--no-providers] [--provider <name>|all]", Description: "Update the binary, refresh .hawp/kit/, and sync all provider overlays from the latest release. Pass --check to check for an available update without installing (exits 1 when an update is ready). Pass --no-providers to skip provider sync (kit-only). Runs outside a HAWP repo without error; kit sync is simply skipped.", Flags: []string{"--check: check whether a newer release is available without installing (exits 1 when an update is ready)", "--no-providers: skip provider overlay sync (kit-only update)", "--provider <name>: sync only this provider (repeatable); use 'all' for every provider in the manifest"}, ExitCodes: "0 = success or already up to date; 1 = error (or update available when --check is passed)", Available: true},
	{Name: "update latest", Usage: "hawp update latest", Description: "Download and install the latest binary only. Does not touch .hawp/kit/ or any provider overlays.", ExitCodes: "0 = success or already up to date; 1 = error", Available: true},
	{Name: "update sync", Usage: "hawp update sync [--provider <name>|all]", Description: "Refresh .hawp/kit/ from the latest release without updating the binary. Provider overlays are opt-in: omit --provider to sync kit only; pass --provider <name> or --provider all to also install/update provider files. Detected providers are updated (skip-protected files untouched); uninstalled providers are freshly installed (seed-if-missing files only written if absent).", Flags: []string{"--provider <name>: also sync this provider overlay (repeatable); use 'all' for every provider in the manifest"}, ExitCodes: "0 = success; 1 = error", Available: true},
	{Name: "update verify", Usage: "hawp update verify", Description: "Check whether a newer release is available without installing anything. Exits 1 when an update is ready so scripts and CI can branch on the status.", ExitCodes: "0 = already up to date; 1 = update available or error", Available: true},
	{Name: "commands", Usage: "hawp commands [--json]", Description: "List every hawp command in this registry — the canonical machine-readable discovery surface for agents.", Flags: []string{"--json: machine-readable output"}, ExitCodes: "0 always", Available: true},
	{Name: "backlog validate", Usage: "hawp backlog validate", Description: "Alias for `check`.", ExitCodes: "same as check", Available: true},
	{Name: "backlog upgrade", Usage: "hawp backlog upgrade [options]", Description: "Alias for `work normalize` (same flags).", ExitCodes: "same as work normalize", Available: true},
	{Name: "db init", Usage: "hawp db init", Description: "Scaffold: plan the ~/.hawp home layout only (no downloads). Superseded by `init` for real provisioning.", ExitCodes: "0 always", Available: true},
	{Name: "index build", Usage: "hawp index build [--scope all|work|kit] [--export <path>]", Description: "Walk .hawp/kit/ and/or .hawp/work/, enrich each document with folder role and backlog metadata (fbf12a93 Slice 1), and print a summary. --export writes the full enriched corpus as JSON.", Flags: []string{"--scope all|work|kit: limit to one corpus (default all)", "--export <path>: write the enriched document corpus as JSON"}, ExitCodes: "0 = success; 1 = error", Available: true},
	{Name: "model pull", Usage: "hawp model pull <hf-org/repo> [--onnx-file <path>]", Description: "Download any Hugging Face ONNX model (with tokenizer) into ~/.hawp/models via hugot's downloader. --onnx-file disambiguates repos with multiple .onnx exports.", Flags: []string{"--onnx-file <path>: exact ONNX file to use when a repo has more than one"}, ExitCodes: "0 = success; 1 = error", Available: true},
	{Name: "embed", Usage: "hawp embed <text>... [--model <hf-org/repo>] [--onnx-file <path>]", Description: "Embed one or more texts via a local ONNX model (hugot's pure-Go backend, no cgo). Defaults to the pinned Xenova/all-MiniLM-L6-v2 model, pulling it on first use.", Flags: []string{"--model <hf-org/repo>: use a different embedding model instead of the default", "--onnx-file <path>: disambiguate when the model repo has multiple .onnx exports"}, ExitCodes: "0 = success; 1 = error", Available: true},
	{Name: "search", Usage: "hawp search <query> [--limit <n>] [--context] [--llm-reshape] [--format markdown|json] [--max-tokens <n>]", Description: "Lexical and vector search over kit/work records. Use --context to format results as LLM-ready markdown or JSON. Use --llm-reshape to additionally restructure the context via an embeddings+LLM pipeline (requires backends configured — see librarian/docs/backends.md; falls back to unreshaped context with a stderr warning if the configured backend is unavailable).", Flags: []string{"--limit <n>: maximum results to return (default 10)", "--context: output LLM-ready context block instead of raw results", "--llm-reshape: reshape context via embeddings+LLM (implies --context)", "--format markdown|json: context output format (default markdown)", "--max-tokens <n>: token budget for context block (default 2000)"}, ExitCodes: "0 = success; 1 = error", Available: true},
	{Name: "context", Usage: "hawp context <query>", Description: "Alias for `search --context` — build LLM-ready context packs (use `hawp search --context` instead).", Available: false},
	{Name: "generate", Usage: "hawp generate <prompt> [--model <hf-org/repo>]", Description: "Planned: local text generation via hugot's ORT/cgo backend (see work item 748609a8) — not yet wired into the default cross-compiled build.", Available: false},
}
